ECHO/OFF
DEFINE/PARAMETER p1 + N
DEFINE/PARAMETER p2 + N
DEFINE/PARAMETER p3 + N
DEFINE/PARAMETER p4 + N
DEFINE/PARAMETER p5 + N
DEFINE/MAXPAR 5

!0
create/tabl TAB1 2 2 TAB1.dat TAB1.fmt

!1
create/tabl TAB2 2 2
CREATE/COLUMN TAB2 TIME "days"
CREATE/COLUMN TAB2 FLUX "erg/s/cm2"

DEFINE/LOCAL start/r/1/1 {p1}
DEFINE/LOCAL end/r/1/1 {p2}
DEFINE/LOCAL step/r/1/1 {p3}

DEFINE/LOCAL n/i/1/1
DEFINE/LOCAL np1/i/1/1
DEFINE/LOCAL iter/i/1/1
DEFINE/LOCAL time/r/1/1
DEFINE/LOCAL flux/r/1/1
DEFINE/LOCAL pi/r/1/1 3.14159265

iter = M$NINT(({end} - {start}) / {step})

!2, 3
DO n = 0 {iter} 1
    np1 = {n} + 1
    time = {start} + {step} * {n}
    flux = {time} + M$SIN({time} / {pi} * 180 * {p4})
    WRITE/TABLE TAB2 :TIME @{np1} {time}
    WRITE/TABLE TAB2 :FLUX @{np1} {flux}
ENDDO

!4
WRITE/TABLE TAB2 :FLUX @1 -{p5}

!5
MERGE/TABLE TAB1 TAB2 TAB

!6
SORT/TABLE TAB :TIME

!7, 8
REGRESSION/LINEAR TAB :FLUX :TIME
SAVE/REGRESSION TAB test
COMPUTE/REGRESSION TAB :FIT1 = test

SELECT/TABLE TAB :FLUX .GE. 0
REGRESSION/LINEAR TAB :FLUX :TIME
SAVE/REGRESSION TAB test
COMPUTE/REGRESSION TAB :FIT2 = test

!9
CREATE/GRAPHICS
PLOT/TABLE TAB :TIME :FLUX p5=1 p6=0
OVERPLOT/TABLE TAB :TIME :FIT1 p5=0 p6=1
OVERPLOT/TABLE TAB :TIME :FIT2 p5=0 p6=3

!10,11
DELETE/COLUMN TAB :FIT2
READ/TAB TAB